<link rel="stylesheet" href="{{ url('frontend/assets/css/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ url('frontend/assets/css/owl.carousel.min.css') }}">
<link rel="stylesheet" href="{{ url('frontend/assets/css/slicknav.css') }}">
<link rel="stylesheet" href="{{ url('frontend/assets/css/flaticon.css') }}">
<link rel="stylesheet" href="{{ url('frontend/assets/css/progressbar_barfiller.css') }}">
<link rel="stylesheet" href="{{ url('frontend/assets/css/gijgo.css') }}">
<link rel="stylesheet" href="{{ url('frontend/assets/css/animate.min.css') }}">
<link rel="stylesheet" href="{{ url('frontend/assets/css/animated-headline.css') }}">
<link rel="stylesheet" href="{{ url('frontend/assets/css/magnific-popup.css') }}">
<link rel="stylesheet" href="{{ url('frontend/assets/css/fontawesome-all.min.css') }}">
<link rel="stylesheet" href="{{ url('frontend/assets/css/themify-icons.css') }}">
<link rel="stylesheet" href="{{ url('frontend/assets/css/slick.css') }}">
<link rel="stylesheet" href="{{ url('frontend/assets/css/nice-select.css') }}">
<link rel="stylesheet" href="{{ url('frontend/assets/css/style.css') }}">
